/**
 * Reading a USBPcap capture back into SysEx.
 *
 * ## About these fixtures
 *
 * They are **hand-built from the two specifications** — pcapng's block layout and USB-MIDI's event
 * packet table — rather than produced by the code under test or by a run of it. That is the whole
 * discipline: a fixture generated by our own writer would agree with our own misreading, and this
 * module's entire job is to be right about somebody else's format.
 *
 * The one thing they cannot prove is that a real Wireshark file matches the specification, which is
 * why the first capture from hardware is the real test. What they do prove is that the framing,
 * the direction split and the SysEx reassembly are right given bytes that follow the spec.
 */

import assert from "node:assert/strict";
import { test } from "node:test";
import { parsePcapng, reassembleUsbMidi, toSyx } from "../src/research/usbcapture.js";

// --- building a pcapng by hand --------------------------------------------------------------------

const LINKTYPE_USBPCAP = 249;

function u16(v: number): number[] {
  return [v & 0xff, (v >> 8) & 0xff];
}
function u32(v: number): number[] {
  return [v & 0xff, (v >> 8) & 0xff, (v >> 16) & 0xff, (v >>> 24) & 0xff];
}

function block(type: number, body: number[]): number[] {
  const total = body.length + 12;
  return [...u32(type), ...u32(total), ...body, ...u32(total)];
}

/** Section header with the little-endian byte-order magic, then one USB interface. */
function preamble(linkType = LINKTYPE_USBPCAP): number[] {
  return [
    ...block(0x0a0d0d0a, [...u32(0x1a2b3c4d), ...u16(1), ...u16(0), ...u32(0xffffffff), ...u32(0xffffffff)]),
    ...block(0x00000001, [...u16(linkType), ...u16(0), ...u32(0)]),
  ];
}

/**
 * A USBPcap packet: the 27-byte pseudo-header, then the payload.
 *
 * `transfer` 3 is bulk, which is what USB-MIDI uses.
 */
function usbPacket(payload: number[], { fromDevice = false, transfer = 3, headerPad = 0 } = {}): number[] {
  const headerLen = 27 + headerPad;
  const header = [
    ...u16(headerLen),
    ...u32(0), ...u32(0), // irpId, 8 bytes
    ...u32(0),            // status
    ...u16(0),            // function
    fromDevice ? 0x01 : 0x00,
    ...u16(1),            // bus
    ...u16(4),            // device
    fromDevice ? 0x81 : 0x01,
    transfer,
    ...u32(payload.length),
    ...new Array<number>(headerPad).fill(0),
  ];
  const data = [...header, ...payload];
  return block(0x00000006, [...u32(0), ...u32(0), ...u32(0), ...u32(data.length), ...u32(data.length), ...data, ...padding(data.length)]);
}

/** pcapng pads packet data to a 4-byte boundary. */
function padding(length: number): number[] {
  return new Array<number>((4 - (length % 4)) % 4).fill(0);
}

/** Split a SysEx message into USB-MIDI event packets, the way a real device does. */
function midiEvents(sysex: number[], cable = 0): number[] {
  const out: number[] = [];
  let at = 0;
  while (sysex.length - at > 3) {
    out.push((cable << 4) | 0x4, sysex[at]!, sysex[at + 1]!, sysex[at + 2]!);
    at += 3;
  }
  const left = sysex.length - at;
  // 0x5 / 0x6 / 0x7 say "ends here, with this many bytes".
  const cin = left === 1 ? 0x5 : left === 2 ? 0x6 : 0x7;
  out.push((cable << 4) | cin, sysex[at] ?? 0, sysex[at + 1] ?? 0, sysex[at + 2] ?? 0);
  return out;
}

const REQUEST = [0xf0, 0x00, 0x20, 0x3c, 0x10, 0x00, 0x01, 0x02, 0xf7];
const REPLY = [0xf0, 0x00, 0x20, 0x3c, 0x10, 0x00, 0x0a, 0x0b, 0x0c, 0x0d, 0xf7];

// --- the direction split, which is the whole point ------------------------------------------------

test("host and device traffic are kept apart", () => {
  // Everything DNX knows about the storage API came from replies, because Web MIDI could only ever
  // hear the device. A decoder that merged the two would be as useless as the captures we have.
  const file = Uint8Array.from([
    ...preamble(),
    ...usbPacket(midiEvents(REQUEST)),
    ...usbPacket(midiEvents(REPLY), { fromDevice: true }),
  ]);

  const traffic = reassembleUsbMidi(parsePcapng(file));

  assert.deepEqual([...toSyx(traffic.toDevice)], REQUEST, "the half we have never seen");
  assert.deepEqual([...toSyx(traffic.fromDevice)], REPLY);
});

test("a message spanning many event packets is put back together whole", () => {
  // A project read is hundreds of thousands of these. Getting the continuation wrong would produce
  // messages that parse and are wrong, which is worse than messages that fail.
  const long = [0xf0, 0x00, 0x20, 0x3c, 0x10, 0x00, ...Array.from({ length: 200 }, (_, i) => i & 0x7f), 0xf7];
  const file = Uint8Array.from([...preamble(), ...usbPacket(midiEvents(long))]);

  const traffic = reassembleUsbMidi(parsePcapng(file));

  assert.equal(traffic.toDevice.length, 1, "one message, however many packets carried it");
  assert.deepEqual([...traffic.toDevice[0]!], long);
});

test("two cables interleaving on one endpoint do not merge", () => {
  const a = [0xf0, 0x01, 0x01, 0x01, 0xf7];
  const b = [0xf0, 0x02, 0x02, 0x02, 0xf7];
  // Interleaved deliberately: cable 0 starts, cable 1 starts and finishes, cable 0 finishes.
  const events = [...midiEvents(a, 0).slice(0, 4), ...midiEvents(b, 1), ...midiEvents(a, 0).slice(4)];
  const file = Uint8Array.from([...preamble(), ...usbPacket(events)]);

  const traffic = reassembleUsbMidi(parsePcapng(file));
  const messages = traffic.toDevice.map((m) => [...m]);

  assert.equal(messages.length, 2);
  assert.ok(messages.some((m) => m[1] === 0x01), "cable 0's message survived the interleave");
  assert.ok(messages.some((m) => m[1] === 0x02), "cable 1's did too");
});

// --- everything that is not SysEx ------------------------------------------------------------------

test("clock and padding are counted, not decoded", () => {
  // A capture of a Digitone is full of F8. Wireshark showed exactly this while the user was setting
  // up: code index 0xF, single byte, MIDI event f8.
  const clock = [0x0f, 0xf8, 0x00, 0x00];
  const zeroes = [0x00, 0x00, 0x00, 0x00];
  const file = Uint8Array.from([...preamble(), ...usbPacket([...clock, ...clock, ...zeroes])]);

  const traffic = reassembleUsbMidi(parsePcapng(file));

  assert.equal(traffic.toDevice.length, 0, "none of that is SysEx");
  assert.equal(traffic.otherEvents, 2, "the two clocks — the padding is not an event");
});

test("a single-byte system common is not mistaken for the end of a SysEx", () => {
  // 0x5 means BOTH "SysEx ends with one byte" and "single-byte system common". With nothing in
  // progress it is the latter, and treating it as a terminator emits a message nobody sent.
  const tuneRequest = [0x05, 0xf6, 0x00, 0x00];
  const file = Uint8Array.from([...preamble(), ...usbPacket(tuneRequest)]);

  const traffic = reassembleUsbMidi(parsePcapng(file));

  assert.deepEqual(traffic.toDevice, []);
  assert.equal(traffic.otherEvents, 1);
});

test("control transfers are ignored — enumeration is not music", () => {
  const file = Uint8Array.from([
    ...preamble(),
    ...usbPacket(midiEvents(REQUEST), { transfer: 2 }),
  ]);
  assert.deepEqual(reassembleUsbMidi(parsePcapng(file)).toDevice, []);
});

test("a longer pseudo-header is honoured rather than assumed away", () => {
  // Control transfers carry extra header fields, so headerLen is not always 27. Reading the payload
  // at a fixed offset works until the first one and then feeds header bytes to a MIDI parser.
  const file = Uint8Array.from([...preamble(), ...usbPacket(midiEvents(REQUEST), { headerPad: 8 })]);
  assert.deepEqual([...toSyx(reassembleUsbMidi(parsePcapng(file)).toDevice)], REQUEST);
});

// --- refusing rather than reporting nothing --------------------------------------------------------

test("a capture from a non-USB interface is refused, not silently empty", () => {
  // "0 packets" and "you captured the wrong interface" look identical otherwise, and that is worth
  // twenty minutes of somebody's evening.
  const ethernet = Uint8Array.from(preamble(1));
  assert.throws(() => parsePcapng(ethernet), /no USB interface/);
});

test("something that is not a pcapng at all says so", () => {
  assert.throws(() => parsePcapng(Uint8Array.from([1, 2, 3, 4, 5, 6, 7, 8, 9])), /section header/);
});

test("a capture cut off mid-write keeps everything before the cut", () => {
  // Stopping a capture is normal. Refusing the whole file because its last block is short would
  // throw away a perfectly good download.
  const whole = [...preamble(), ...usbPacket(midiEvents(REQUEST)), ...usbPacket(midiEvents(REPLY), { fromDevice: true })];
  const cut = Uint8Array.from(whole.slice(0, whole.length - 20));

  const traffic = reassembleUsbMidi(parsePcapng(cut));
  assert.deepEqual([...toSyx(traffic.toDevice)], REQUEST, "the complete message survives the cut");
});
