/**
 * Write `web/src/version.ts` from the one place the version lives.
 *
 * ## Why generated rather than typed into a file
 *
 * A version string somebody edits by hand is a version string that is wrong the first time
 * somebody forgets. `package.json` is the single source, and the commit comes from git at the
 * moment the build runs, so the two together name exactly the code that is serving the page.
 *
 * ## Why the commit, and not only the version
 *
 * The version is what you quote in a changelog. **The commit is what makes a bug report
 * actionable**: DNX is a static site with no release cadence, so two people on "v0.9.0-beta.1"
 * can be a fortnight apart. The short hash closes that gap, and a `+` marks a working tree with
 * uncommitted changes, because a build from a dirty tree matches no commit at all.
 *
 * ## Why the output is not committed
 *
 * It would change on every commit and dirty the tree on every dev build. It is in `.gitignore`,
 * and both `build:web` and `verify` run this first so the file always exists before `tsc` looks
 * for it. A fresh clone that runs neither has no `version.ts`, which is why nothing outside the
 * page's own display may import it.
 */

import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "web", "src", "version.ts");

/** The short commit, with `+` when the tree has changes that are in no commit. */
function commit() {
  try {
    const at = execFileSync("git", ["rev-parse", "--short", "HEAD"], { cwd: ROOT }).toString().trim();
    const dirty = execFileSync("git", ["status", "--porcelain"], { cwd: ROOT }).toString().trim();
    return dirty ? `${at}+` : at;
  } catch {
    // A tarball, or git is not installed. The version alone is still true.
    return "";
  }
}

const { version } = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));
const at = commit();

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `/**
 * **Generated by \`scripts/version.mjs\`. Do not edit — and do not commit.**
 *
 * Written before every \`build:web\` and every \`verify\`, from \`package.json\` and \`git\`.
 * See that script for why it is generated rather than checked in.
 */

/** The release, from \`package.json\`. */
export const DNX_VERSION = ${JSON.stringify(version)};

/** The short commit this was built from, \`+\` if the tree had uncommitted changes. Empty outside git. */
export const DNX_COMMIT = ${JSON.stringify(at)};

/** What the page shows: the release, and the commit when there is one. */
export const DNX_BUILD = ${JSON.stringify(at ? `v${version} · ${at}` : `v${version}`)};
`,
  "utf8",
);

console.log(`version.ts: v${version}${at ? ` · ${at}` : ""}`);
