/**
 * The empty pattern to write when a slot is vacated.
 *
 * Deleting a pattern, or moving one and leaving a hole, both need *something* to put in the
 * slot. A patternKit contains regions whose meaning we have never established — 160 bytes
 * before the kit's MIDI records and 500 trailing at offset 10,252 — so writing zeros there
 * would be inventing device state. The blank is therefore **captured from a project the
 * device initialised**, not constructed. elk-herd embeds blank data for exactly this reason
 * and says so plainly: it "contains many fields elk-herd doesn't manage or decode".
 *
 * `blankdata.ts` holds the captured bytes and is generated by `npm run extract-blank`, which
 * refuses any project whose empty patterns disagree with one another — the test that
 * separates a device's initialisation default from an importer's idea of empty. The two
 * differ by thousands of bytes, so the distinction is not academic.
 *
 * ## Two fields are per-slot, everything else is constant
 *
 * Measured across the corpus: two blanks in the same device-initialised project differ in
 * exactly two places.
 *
 * 1. **The slot index**, since a pattern record stores the slot it believes it occupies.
 * 2. **The kit name**, which the device leaves empty for an untouched kit.
 *
 * Both are patched here at write time, which is why one captured record serves all 128
 * slots on both families.
 */

import { type Device } from "./device.js";
import { DN1_BLANK, DN2_BLANK, decodeBlank } from "./blankdata.js";

/**
 * Where a kit stores its 16-byte name.
 *
 * The families differ: the DN2 kit record opens with `BEEFBACE` before its version field,
 * the DN1's does not, so every subsequent offset shifts by four.
 */
const KIT_NAME_OFFSET: Record<Device["kind"], number> = { dn1: 4, dn2: 8 };
const KIT_NAME_SIZE = 16;

/** Decoded once — the RLE and base64 work should not be repeated per slot cleared. */
const CACHE = new Map<Device["kind"], { pattern: Uint8Array; kit: Uint8Array }>();

function decoded(kind: Device["kind"]): { pattern: Uint8Array; kit: Uint8Array } {
  const hit = CACHE.get(kind);
  if (hit) return hit;
  const value = decodeBlank(kind === "dn1" ? DN1_BLANK : DN2_BLANK);
  CACHE.set(kind, value);
  return value;
}

/** Provenance of the blank this device would write, for reporting in a preview. */
export function blankSource(device: Device): string {
  const blank = device.kind === "dn1" ? DN1_BLANK : DN2_BLANK;
  return `${blank.source} slot ${blank.slot}`;
}

/**
 * A blank patternKit ready to be written at `slot`.
 *
 * Returns fresh copies, so a caller can write into them without disturbing the cached
 * originals or another slot's blank.
 */
export function blankPatternKit(
  device: Device,
  slot: number,
): { pattern: Uint8Array; kit: Uint8Array } {
  const source = decoded(device.kind);
  const pattern = Uint8Array.from(source.pattern);
  const kit = Uint8Array.from(source.kit);

  // The record carries the slot it believes it occupies.
  pattern[device.slotIndexOffset] = slot;

  // An untouched kit has no name on either family. Clearing it rather than trusting the
  // captured bytes means the capture slot's name can never leak into every cleared slot.
  const nameAt = KIT_NAME_OFFSET[device.kind];
  kit.fill(0, nameAt, nameAt + KIT_NAME_SIZE);

  return { pattern, kit };
}

/** True when the sizes of the captured blank match the device's layout. */
export function blankFits(device: Device): boolean {
  const source = decoded(device.kind);
  return (
    source.pattern.length === device.layout.patternSize &&
    source.kit.length === device.layout.kitSize
  );
}
